# Generated by Django 5.0.1 on 2024-02-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dqmio_file_indexer", "0002_badfileindex"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fileindex",
            index=models.Index(fields=["file_path"], name="dqmio_file__file_pa_7ac107_idx"),
        ),
        migrations.AddIndex(
            model_name="fileindex",
            index=models.Index(fields=["data_era"], name="dqmio_file__data_er_e23f71_idx"),
        ),
        migrations.AddIndex(
            model_name="fileindex",
            index=models.Index(fields=["st_size"], name="dqmio_file__st_size_205220_idx"),
        ),
        migrations.AddIndex(
            model_name="fileindex",
            index=models.Index(fields=["status"], name="dqmio_file__status_ab4017_idx"),
        ),
        migrations.AddConstraint(
            model_name="badfileindex",
            constraint=models.UniqueConstraint(fields=("file_path",), name="unique_bad_file_path"),
        ),
    ]
