# Generated by Django 4.0.3 on 2022-03-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistogramDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FilePathField(help_text='Path where the file is stored', path='/home/mpliax/Desktop/tmp', recursive=True)),
                ('filesize', models.PositiveIntegerField(blank=True, default=0, help_text="The data file's size (bytes)")),
                ('data_era', models.CharField(help_text='The era that the data refers to (e.g. 2018A', max_length=5)),
                ('percentage_processed', models.FloatField(default=0.0, help_text='Percentage of file which has been processed and added to the DB')),
                ('granularity', models.CharField(choices=[('run', 'Run'), ('lum', 'Lumisection')], default='run', help_text='The granularity of the data contained in the data file (either whole run or lumisections)', max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='histogramdatafile',
            constraint=models.UniqueConstraint(fields=('filepath',), name='unique_filepath'),
        ),
    ]
