# Generated by Django 4.0.3 on 2022-03-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histogram_file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='histogramdatafile',
            name='data_dimensionality',
            field=models.PositiveIntegerField(choices=[(1, '1D'), (2, '2D')], default=1),
        ),
        migrations.AlterField(
            model_name='histogramdatafile',
            name='data_era',
            field=models.CharField(help_text='The era that the data refers to (e.g. 2018A)', max_length=5),
        ),
    ]
