# Generated by Django 4.0.4 on 2022-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("histogram_file_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="histogramdatafile",
            name="filepath",
            field=models.CharField(
                help_text="Path where the file is stored", max_length=255
            ),
        ),
    ]
