# Generated by Django 4.0.3 on 2022-03-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histogram_file_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histogramdatafile',
            name='percentage_processed',
        ),
        migrations.AddField(
            model_name='histogramdatafile',
            name='entries_processed',
            field=models.PositiveIntegerField(default=0, help_text='Number of histogram entries that have been extracted from the file'),
        ),
        migrations.AddField(
            model_name='histogramdatafile',
            name='entries_total',
            field=models.PositiveIntegerField(default=0, help_text='Total number of entries contained in this histogram file'),
        ),
    ]
