# Generated by Django 4.0.3 on 2022-03-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histogram_file_manager', '0002_remove_histogramdatafile_percentage_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='histogramdatafile',
            name='data_dimensionality',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1D'), (2, '2D')], default=1),
        ),
        migrations.AlterField(
            model_name='histogramdatafile',
            name='data_era',
            field=models.CharField(blank=True, help_text='The era that the data refers to (e.g. 2018A)', max_length=5),
        ),
        migrations.AlterField(
            model_name='histogramdatafile',
            name='filepath',
            field=models.FilePathField(help_text='Path where the file is stored', match='.*\\.csv', max_length=255, path='~/Desktop/tmp', recursive=True),
        ),
        migrations.AlterField(
            model_name='histogramdatafile',
            name='filesize',
            field=models.PositiveIntegerField(default=0, help_text="The data file's size (bytes)"),
        ),
    ]
