# Generated by Django 4.1.3 on 2022-12-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histogram_file_manager', '0005_alter_histogramdatafile_data_dimensionality'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistogramDataFileContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dimensionality', models.PositiveIntegerField(blank=True, choices=[(0, 'Unknown'), (1, '1D'), (2, '2D')], default=0)),
                ('granularity', models.CharField(choices=[('unk', 'Unknown'), ('run', 'Run'), ('lum', 'Lumisection')], default='unk', help_text='The granularity of the data contained in the data file (either whole run or lumisections).', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='histogramdatafile',
            name='data_dimensionality',
        ),
        migrations.RemoveField(
            model_name='histogramdatafile',
            name='granularity',
        ),
        migrations.AddField(
            model_name='histogramdatafile',
            name='contents',
            field=models.ManyToManyField(to='histogram_file_manager.histogramdatafilecontents'),
        ),
    ]
