###############################
# BUILDER IMAGE
###############################

FROM node:20.11-bookworm as builder

WORKDIR /usr/src/app

COPY . /usr/src/app/

RUN yarn install && yarn build:prod

###############################
# FINAL IMAGE
###############################

FROM nginx:stable-alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html
COPY --from=builder /usr/src/app/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
