# Generated by Django 3.2.8 on 2021-12-12 20:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lumisections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LumisectionHisto1D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('entries', models.IntegerField(blank=True, null=True)),
                ('x_min', models.FloatField(blank=True, null=True)),
                ('x_max', models.FloatField(blank=True, null=True)),
                ('x_bin', models.IntegerField(blank=True, null=True)),
                ('lumisection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumisections.lumisection')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lumisectionhisto1d',
            constraint=models.UniqueConstraint(fields=('lumisection', 'title'), name='unique run / ls / 1d histogram combination'),
        ),
    ]
