# Generated by Django 4.0.3 on 2022-03-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('histogram_file_manager', '0003_alter_histogramdatafile_filepath'),
        ('lumisection_histos1D', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumisectionhisto1d',
            name='source_data_file',
            field=models.ForeignKey(blank=True, help_text='Source data file that the specific Histogram was read from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='histogram_file_manager.histogramdatafile'),
        ),
    ]
