# Generated by Django 4.0.6 on 2022-07-15 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_taking_objects', '0003_run_unique run number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rr_is_pixel_good', models.BooleanField(null=True)),
                ('rr_is_strip_good', models.BooleanField(null=True)),
                ('rr_is_ecal_good', models.BooleanField(null=True)),
                ('rr_is_hcal_good', models.BooleanField(null=True)),
                ('rr_is_dt_good', models.BooleanField(null=True)),
                ('rr_is_csc_good', models.BooleanField(null=True)),
                ('rr_is_tracking_good', models.BooleanField(null=True)),
                ('rr_is_muon_good', models.BooleanField(null=True)),
                ('rr_is_egamma_good', models.BooleanField(null=True)),
                ('rr_is_tau_good', models.BooleanField(null=True)),
                ('rr_is_jetmet_good', models.BooleanField(null=True)),
                ('rr_is_btag_good', models.BooleanField(null=True)),
                ('rr_frac_pixel_good', models.FloatField(null=True)),
                ('rr_frac_strip_good', models.FloatField(null=True)),
                ('rr_frac_ecal_good', models.FloatField(null=True)),
                ('rr_frac_hcal_good', models.FloatField(null=True)),
                ('rr_frac_dt_good', models.FloatField(null=True)),
                ('rr_frac_csc_good', models.FloatField(null=True)),
                ('rr_frac_tracking_good', models.FloatField(null=True)),
                ('rr_frac_muon_good', models.FloatField(null=True)),
                ('rr_frac_egamma_good', models.FloatField(null=True)),
                ('rr_frac_tau_good', models.FloatField(null=True)),
                ('rr_frac_jetmet_good', models.FloatField(null=True)),
                ('rr_frac_btag_good', models.FloatField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='data_taking_objects.run')),
            ],
        ),
        migrations.CreateModel(
            name='LumisectionCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rr_is_golden_json', models.BooleanField(null=True)),
                ('rr_is_pixel_good', models.BooleanField(null=True)),
                ('rr_is_strip_good', models.BooleanField(null=True)),
                ('rr_is_ecal_good', models.BooleanField(null=True)),
                ('rr_is_hcal_good', models.BooleanField(null=True)),
                ('rr_is_dt_good', models.BooleanField(null=True)),
                ('rr_is_csc_good', models.BooleanField(null=True)),
                ('rr_is_tracking_good', models.BooleanField(null=True)),
                ('rr_is_muon_good', models.BooleanField(null=True)),
                ('rr_is_egamma_good', models.BooleanField(null=True)),
                ('rr_is_tau_good', models.BooleanField(null=True)),
                ('rr_is_jetmet_good', models.BooleanField(null=True)),
                ('rr_is_btag_good', models.BooleanField(null=True)),
                ('lumisection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='data_taking_objects.lumisection')),
            ],
        ),
    ]
