# Generated by Django 4.0.6 on 2022-07-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_taking_certification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lumisectioncertification',
            name='rr_is_pixel_good',
            field=models.BooleanField(null=True),
        ),
    ]
