# Generated by Django 5.0.1 on 2024-01-26 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dqmio_etl", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RunHistogram",
        ),
    ]
