# Generated by Django 5.0.1 on 2024-02-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dqmio_etl", "0002_delete_runhistogram"),
        ("dqmio_file_indexer", "0003_fileindex_dqmio_file__file_pa_7ac107_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lumisection",
            index=models.Index(fields=["run"], name="dqmio_etl_l_run_id_994c90_idx"),
        ),
        migrations.AddIndex(
            model_name="lumisection",
            index=models.Index(fields=["ls_number"], name="dqmio_etl_l_ls_numb_7561f3_idx"),
        ),
        migrations.AddIndex(
            model_name="lumisectionhistogram1d",
            index=models.Index(fields=["lumisection"], name="dqmio_etl_l_lumisec_e3ab8f_idx"),
        ),
        migrations.AddIndex(
            model_name="lumisectionhistogram1d",
            index=models.Index(fields=["title"], name="dqmio_etl_l_title_cb5ea9_idx"),
        ),
        migrations.AddIndex(
            model_name="lumisectionhistogram1d",
            index=models.Index(fields=["entries"], name="dqmio_etl_l_entries_692d4b_idx"),
        ),
        migrations.AddIndex(
            model_name="lumisectionhistogram2d",
            index=models.Index(fields=["lumisection"], name="dqmio_etl_l_lumisec_f70805_idx"),
        ),
        migrations.AddIndex(
            model_name="lumisectionhistogram2d",
            index=models.Index(fields=["title"], name="dqmio_etl_l_title_6638d7_idx"),
        ),
        migrations.AddIndex(
            model_name="lumisectionhistogram2d",
            index=models.Index(fields=["entries"], name="dqmio_etl_l_entries_12829f_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["run_number"], name="dqmio_etl_r_run_num_e30e8f_idx"),
        ),
    ]
