# Generated by Django 5.0.1 on 2024-03-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dqmio_etl", "0003_lumisection_dqmio_etl_l_run_id_994c90_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="period",
            field=models.CharField(blank=True, default="", max_length=1),
        ),
    ]
