# Generated by Django 4.0.3 on 2022-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LumisectionCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rr_is_golden_json', models.BooleanField(null=True)),
                ('rr_is_pixel_good', models.FloatField(null=True)),
                ('rr_is_strip_good', models.BooleanField(null=True)),
                ('rr_is_ecal_good', models.BooleanField(null=True)),
                ('rr_is_hcal_good', models.BooleanField(null=True)),
                ('rr_is_dt_good', models.BooleanField(null=True)),
                ('rr_is_csc_good', models.BooleanField(null=True)),
                ('rr_is_tracking_good', models.BooleanField(null=True)),
                ('rr_is_muon_good', models.BooleanField(null=True)),
                ('rr_is_egamma_good', models.BooleanField(null=True)),
                ('rr_is_tau_good', models.BooleanField(null=True)),
                ('rr_is_jetmet_good', models.BooleanField(null=True)),
                ('rr_is_btag_good', models.BooleanField(null=True)),
            ],
        ),
    ]
