# Generated by Django 4.0.3 on 2022-03-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lumisection_certification', '0001_initial'),
        ('lumisections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumisectioncertification',
            name='lumisection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumisections.lumisection'),
        ),
    ]
