# Generated by Django 4.0.3 on 2022-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('storagetype', models.CharField(choices=[('postgres', 'Postgres'), ('eos', 'EOS'), ('external', 'External')], max_length=50)),
                ('granularity', models.CharField(choices=[('fill', 'Fill'), ('run', 'Run'), ('lumi', 'Lumisection')], max_length=50)),
                ('api', models.TextField(blank=True)),
                ('api_description', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('scripts', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('data_view', models.TextField(blank=True)),
            ],
        ),
    ]
