# Generated by Django 3.2.8 on 2022-02-11 20:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumisection_histos2D', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lumisectionhisto2d',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None),
        ),
    ]
