# Generated by Django 3.2.8 on 2022-04-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_taking_objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lumisection',
            options={'ordering': ['run__run_number', 'ls_number']},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ['run_number']},
        ),
    ]
