# Generated by Django 4.0.6 on 2022-07-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_taking_objects', '0003_run_unique run number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='id',
        ),
        migrations.AlterField(
            model_name='run',
            name='run_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
