# Generated by Django 3.2.8 on 2021-10-22 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunHisto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('primary_dataset', models.CharField(max_length=220)),
                ('path', models.CharField(max_length=220)),
                ('title', models.CharField(max_length=220)),
                ('entries', models.IntegerField(null=True)),
                ('mean', models.FloatField(null=True)),
                ('rms', models.FloatField(null=True)),
                ('skewness', models.FloatField(null=True)),
                ('kurtosis', models.FloatField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.run')),
            ],
        ),
    ]
