# Generated by Django 3.2.8 on 2021-11-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_histos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runhisto',
            name='entries',
            field=models.BigIntegerField(null=True),
        ),
    ]
