# Generated by Django 5.0.1 on 2024-01-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path where the file is stored', max_length=255)),
                ('data_era', models.CharField(default='Unknown', help_text='The era that the data refers to (e.g. 2018A)', max_length=7)),
                ('n_entries', models.PositiveIntegerField(default=0, help_text='Total number of entries contained in this histogram file')),
                ('n_entries_ingested', models.PositiveIntegerField(default=0, help_text='Number of histogram entries that have been extracted from the file')),
                ('st_size', models.FloatField(default=0, help_text="The data file's size in bytes")),
                ('st_ctime', models.DateTimeField(help_text="Time of files's last status change in filesystem")),
                ('st_mtime', models.DateTimeField(help_text="Time of files's last modification in filesystem")),
                ('st_itime', models.DateTimeField(auto_now_add=True, help_text='Time when file was indexed in database')),
                ('st_imtime', models.DateTimeField(auto_now=True, help_text='Time when index entry was modified in database')),
                ('status_rh', models.CharField(default='INDEXED', help_text='Indicate the processing status of run-histogram within the file', max_length=30)),
                ('status_h1d', models.CharField(default='INDEXED', help_text='Indicate the processing status of 1d-histograms within the file', max_length=30)),
                ('status_h2d', models.CharField(default='INDEXED', help_text='Indicate the processing status of 2d-histograms within the file', max_length=30)),
            ],
        ),
        migrations.AddConstraint(
            model_name='fileindex',
            constraint=models.UniqueConstraint(fields=('file_path',), name='unique_file_path'),
        ),
    ]
