# Generated by Django 4.0.3 on 2022-03-24 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('histograms', '0001_initial'),
        ('data_taking_objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Model used by the Strategy', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, help_text='Extra details that describe the Task')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('testing_lumisections', models.ManyToManyField(blank=True, help_text='Lumisections used for testing the model', related_name='tasks_using_for_testing', to='data_taking_objects.lumisection')),
                ('testing_runs', models.ManyToManyField(blank=True, help_text='Runs used as a whole for testing the model', related_name='tasks_using_for_testing', to='data_taking_objects.run')),
                ('training_lumisections', models.ManyToManyField(blank=True, help_text='Lumisections used for training the model', related_name='tasks_using_for_training', to='data_taking_objects.lumisection')),
                ('training_runs', models.ManyToManyField(blank=True, help_text='Runs used as a whole for training the model', related_name='tasks_using_for_training', to='data_taking_objects.run')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('lumisection_histograms_1d', models.ManyToManyField(blank=True, help_text='Specific LumisectionHistogram1D used to make the prediction [Optional]', related_name='predictions', to='histograms.lumisectionhistogram1d')),
                ('lumisection_histograms_2d', models.ManyToManyField(blank=True, help_text='Specific LumisectionHistogram2D used to make the prediction [Optional]', related_name='predictions', to='histograms.lumisectionhistogram2d')),
                ('run_histograms', models.ManyToManyField(blank=True, help_text='Specific RunHistograms used to make the prediction [Optional]', related_name='predictions', to='histograms.runhistogram')),
                ('strategy', models.ForeignKey(help_text='The Strategy used to make the prediction', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='challenge.strategy')),
                ('task', models.ForeignKey(help_text='The Task used to make the prediction', on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='challenge.task')),
            ],
        ),
    ]
