# Generated by Django 3.2.8 on 2022-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="metadata",
            field=models.CharField(
                blank=True,
                help_text="Extra details that describe the Task",
                max_length=200,
            ),
        ),
    ]
