# Generated by Django 3.2.8 on 2022-05-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_alter_task_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Whatever', max_length=200),
            preserve_default=False,
        ),
    ]
