# Generated by Django 4.1.1 on 2022-10-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenge", "0004_task_unique task name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="strategy",
            options={"verbose_name_plural": "Strategies"},
        ),
    ]
