# Generated by Django 4.0.3 on 2022-03-23 13:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('histogram_file_manager', '__first__'),
        ('runs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistogramBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=220)),
                ('source_data_file', models.ForeignKey(blank=True, help_text='Source data file that the specific Histogram was read from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to='histogram_file_manager.histogramdatafile')),
            ],
        ),
        migrations.CreateModel(
            name='LumisectionHistogramBase',
            fields=[
                ('histogrambase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='histograms.histogrambase')),
                ('entries', models.IntegerField(blank=True, null=True)),
            ],
            bases=('histograms.histogrambase',),
        ),
        migrations.CreateModel(
            name='LumisectionHistogram1D',
            fields=[
                ('lumisectionhistogrambase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='histograms.lumisectionhistogrambase')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('x_min', models.FloatField(blank=True, null=True)),
                ('x_max', models.FloatField(blank=True, null=True)),
                ('x_bin', models.IntegerField(blank=True, null=True)),
            ],
            bases=('histograms.lumisectionhistogrambase',),
        ),
        migrations.CreateModel(
            name='LumisectionHistogram2D',
            fields=[
                ('lumisectionhistogrambase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='histograms.lumisectionhistogrambase')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, size=None)),
                ('x_min', models.FloatField(blank=True, null=True)),
                ('x_max', models.FloatField(blank=True, null=True)),
                ('x_bin', models.IntegerField(blank=True, null=True)),
                ('y_max', models.FloatField(blank=True, null=True)),
                ('y_min', models.FloatField(blank=True, null=True)),
                ('y_bin', models.IntegerField(blank=True, null=True)),
            ],
            bases=('histograms.lumisectionhistogrambase',),
        ),
        migrations.CreateModel(
            name='RunHistogram',
            fields=[
                ('histogrambase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='histograms.histogrambase')),
                ('primary_dataset', models.CharField(max_length=220)),
                ('path', models.CharField(max_length=220)),
                ('entries', models.BigIntegerField(null=True)),
                ('mean', models.FloatField(null=True)),
                ('rms', models.FloatField(null=True)),
                ('skewness', models.FloatField(null=True)),
                ('kurtosis', models.FloatField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runs.run')),
            ],
            bases=('histograms.histogrambase',),
        ),
    ]
