# Generated by Django 4.0.6 on 2022-07-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_taking_objects', '0003_run_unique run number'),
        ('histogram_file_manager', '0004_alter_histogramdatafile_data_dimensionality_and_more'),
        ('histograms', '0006_alter_runhistogram_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lumisectionhistogram1d',
            name='lumisection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_histograms', to='data_taking_objects.lumisection'),
        ),
        migrations.AlterField(
            model_name='lumisectionhistogram1d',
            name='source_data_file',
            field=models.ForeignKey(blank=True, help_text='Source data file that the specific Histogram was read from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='histogram_file_manager.histogramdatafile'),
        ),
        migrations.AlterField(
            model_name='lumisectionhistogram2d',
            name='lumisection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_histograms', to='data_taking_objects.lumisection'),
        ),
        migrations.AlterField(
            model_name='lumisectionhistogram2d',
            name='source_data_file',
            field=models.ForeignKey(blank=True, help_text='Source data file that the specific Histogram was read from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='histogram_file_manager.histogramdatafile'),
        ),
        migrations.AlterField(
            model_name='runhistogram',
            name='source_data_file',
            field=models.ForeignKey(blank=True, help_text='Source data file that the specific Histogram was read from, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s', to='histogram_file_manager.histogramdatafile'),
        ),
    ]
